# Generated by Django 4.2.16 on 2025-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title_url',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(),
        ),
    ]
